controllers:
    resource: '../src/Controller/'
    type: 'annotation'

login:
    path: /login
    controller: App\Controller\AuthController::login
registre:
    path: /register
    controller: App\Controller\RegistrationController::register
home:
    path: /back
    controller: App\Controller\HomeController::index
front:
    path: /front
    controller: App\Controller\HomeController::indexFront
